### PR TITLE
Read type from Enviroment Variable.

### PR DESCRIPTION
**Pull request by guerremdq**
Hi,

We need to be able to change the type using enviroment variables.

Thanks

### CODE REVIEW

**Comment by idohalevi** [comment]
@guerremdq 
Please update the README before we merge

**Comment by guerremdq** [comment]
@idohalevi Done. Thanks!

**Comment by guerremdq** [comment]
@idohalevi Are you going to create a new release?

**Comment by idohalevi** [comment]
@guerremdq 
Yes, I will work on it today.

**Comment by guerremdq** [comment]
Awesome! Thanks! :)

**Comment by idohalevi** [comment]
@guerremdq 
The release is done, let us know if you have any issues

**Pull request merged**
